[package]
name = "ebpf-tail-trace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcc = { version = "0.0.33" }
clap = { version = "4", features = ["derive"] }
itertools = "0.10"
